#pragma once

#include <Windows.h>

#define VERSION L"1.1"

extern const char* const TIME_SIGNATURE_CODE;
extern const char* const VISION_SWITCH_SIGNATURE_CODE;
extern const BYTE VISION_SWITCH_EXPECTED_OPCODE;
extern const BYTE VISION_SWITCH_TARGET_OPCODE;
extern const char* const ATTACK_RANGE_SIGNATURE_CODE;
extern const BYTE ATTACK_RANGE_EXPECTED_OPCODE;
extern const BYTE ATTACK_RANGE_TARGET_OPCODE;
extern const char* const ANTI_RECOIL_RELEASE_START_SIGNATURE_CODE;
extern const BYTE ANTI_RECOIL_RELEASE_START_EXPECTED_OPCODE;
extern const BYTE ANTI_RECOIL_RELEASE_START_TARGET_OPCODE;
extern const char* const ANTI_RECOIL_RELEASE_END_SIGNATURE_CODE;
extern const BYTE ANTI_RECOIL_RELEASE_END_EXPECTED_OPCODE;
extern const BYTE ANTI_RECOIL_RELEASE_END_TARGET_OPCODE;
extern const wchar_t* const CONFIG_PATH;
extern const WCHAR APP_CODE[512];
